// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: e_macaroon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "e_macaroon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace macaroons {

namespace {

const ::google::protobuf::Descriptor* e_macaroon_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  e_macaroon_reflection_ = NULL;
const ::google::protobuf::Descriptor* e_macaroon_Endorsement_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  e_macaroon_Endorsement_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_e_5fmacaroon_2eproto() {
  protobuf_AddDesc_e_5fmacaroon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "e_macaroon.proto");
  GOOGLE_CHECK(file != NULL);
  e_macaroon_descriptor_ = file->message_type(0);
  static const int e_macaroon_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon, macaroon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon, endorsements_),
  };
  e_macaroon_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      e_macaroon_descriptor_,
      e_macaroon::default_instance_,
      e_macaroon_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(e_macaroon));
  e_macaroon_Endorsement_descriptor_ = e_macaroon_descriptor_->nested_type(0);
  static const int e_macaroon_Endorsement_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, kind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, certname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, hash_),
  };
  e_macaroon_Endorsement_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      e_macaroon_Endorsement_descriptor_,
      e_macaroon_Endorsement::default_instance_,
      e_macaroon_Endorsement_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(e_macaroon_Endorsement, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(e_macaroon_Endorsement));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_e_5fmacaroon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    e_macaroon_descriptor_, &e_macaroon::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    e_macaroon_Endorsement_descriptor_, &e_macaroon_Endorsement::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_e_5fmacaroon_2eproto() {
  delete e_macaroon::default_instance_;
  delete e_macaroon_reflection_;
  delete e_macaroon_Endorsement::default_instance_;
  delete e_macaroon_Endorsement_reflection_;
}

void protobuf_AddDesc_e_5fmacaroon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020e_macaroon.proto\022\tmacaroons\"\242\001\n\ne_maca"
    "roon\022\020\n\010macaroon\030\001 \002(\t\0227\n\014endorsements\030\002"
    " \003(\0132!.macaroons.e_macaroon.Endorsement\032"
    "I\n\013Endorsement\022\014\n\004kind\030\001 \002(\t\022\014\n\004name\030\002 \002"
    "(\t\022\020\n\010certname\030\003 \002(\t\022\014\n\004hash\030\004 \002(\t", 194);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "e_macaroon.proto", &protobuf_RegisterTypes);
  e_macaroon::default_instance_ = new e_macaroon();
  e_macaroon_Endorsement::default_instance_ = new e_macaroon_Endorsement();
  e_macaroon::default_instance_->InitAsDefaultInstance();
  e_macaroon_Endorsement::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_e_5fmacaroon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_e_5fmacaroon_2eproto {
  StaticDescriptorInitializer_e_5fmacaroon_2eproto() {
    protobuf_AddDesc_e_5fmacaroon_2eproto();
  }
} static_descriptor_initializer_e_5fmacaroon_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int e_macaroon_Endorsement::kKindFieldNumber;
const int e_macaroon_Endorsement::kNameFieldNumber;
const int e_macaroon_Endorsement::kCertnameFieldNumber;
const int e_macaroon_Endorsement::kHashFieldNumber;
#endif  // !_MSC_VER

e_macaroon_Endorsement::e_macaroon_Endorsement()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void e_macaroon_Endorsement::InitAsDefaultInstance() {
}

e_macaroon_Endorsement::e_macaroon_Endorsement(const e_macaroon_Endorsement& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void e_macaroon_Endorsement::SharedCtor() {
  _cached_size_ = 0;
  kind_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  certname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  hash_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

e_macaroon_Endorsement::~e_macaroon_Endorsement() {
  SharedDtor();
}

void e_macaroon_Endorsement::SharedDtor() {
  if (kind_ != &::google::protobuf::internal::kEmptyString) {
    delete kind_;
  }
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (certname_ != &::google::protobuf::internal::kEmptyString) {
    delete certname_;
  }
  if (hash_ != &::google::protobuf::internal::kEmptyString) {
    delete hash_;
  }
  if (this != default_instance_) {
  }
}

void e_macaroon_Endorsement::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* e_macaroon_Endorsement::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return e_macaroon_Endorsement_descriptor_;
}

const e_macaroon_Endorsement& e_macaroon_Endorsement::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_e_5fmacaroon_2eproto();
  return *default_instance_;
}

e_macaroon_Endorsement* e_macaroon_Endorsement::default_instance_ = NULL;

e_macaroon_Endorsement* e_macaroon_Endorsement::New() const {
  return new e_macaroon_Endorsement;
}

void e_macaroon_Endorsement::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_kind()) {
      if (kind_ != &::google::protobuf::internal::kEmptyString) {
        kind_->clear();
      }
    }
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_certname()) {
      if (certname_ != &::google::protobuf::internal::kEmptyString) {
        certname_->clear();
      }
    }
    if (has_hash()) {
      if (hash_ != &::google::protobuf::internal::kEmptyString) {
        hash_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool e_macaroon_Endorsement::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string kind = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_kind()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->kind().data(), this->kind().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // required string name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_certname;
        break;
      }

      // required string certname = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_certname:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_certname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->certname().data(), this->certname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_hash;
        break;
      }

      // required string hash = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hash:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hash()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->hash().data(), this->hash().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void e_macaroon_Endorsement::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string kind = 1;
  if (has_kind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->kind(), output);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->name(), output);
  }

  // required string certname = 3;
  if (has_certname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->certname().data(), this->certname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->certname(), output);
  }

  // required string hash = 4;
  if (has_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->hash().data(), this->hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->hash(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* e_macaroon_Endorsement::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string kind = 1;
  if (has_kind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->kind(), target);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // required string certname = 3;
  if (has_certname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->certname().data(), this->certname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->certname(), target);
  }

  // required string hash = 4;
  if (has_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->hash().data(), this->hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->hash(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int e_macaroon_Endorsement::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string kind = 1;
    if (has_kind()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->kind());
    }

    // required string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required string certname = 3;
    if (has_certname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->certname());
    }

    // required string hash = 4;
    if (has_hash()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->hash());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void e_macaroon_Endorsement::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const e_macaroon_Endorsement* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const e_macaroon_Endorsement*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void e_macaroon_Endorsement::MergeFrom(const e_macaroon_Endorsement& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_kind()) {
      set_kind(from.kind());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_certname()) {
      set_certname(from.certname());
    }
    if (from.has_hash()) {
      set_hash(from.hash());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void e_macaroon_Endorsement::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void e_macaroon_Endorsement::CopyFrom(const e_macaroon_Endorsement& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool e_macaroon_Endorsement::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void e_macaroon_Endorsement::Swap(e_macaroon_Endorsement* other) {
  if (other != this) {
    std::swap(kind_, other->kind_);
    std::swap(name_, other->name_);
    std::swap(certname_, other->certname_);
    std::swap(hash_, other->hash_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata e_macaroon_Endorsement::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = e_macaroon_Endorsement_descriptor_;
  metadata.reflection = e_macaroon_Endorsement_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int e_macaroon::kMacaroonFieldNumber;
const int e_macaroon::kEndorsementsFieldNumber;
#endif  // !_MSC_VER

e_macaroon::e_macaroon()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void e_macaroon::InitAsDefaultInstance() {
}

e_macaroon::e_macaroon(const e_macaroon& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void e_macaroon::SharedCtor() {
  _cached_size_ = 0;
  macaroon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

e_macaroon::~e_macaroon() {
  SharedDtor();
}

void e_macaroon::SharedDtor() {
  if (macaroon_ != &::google::protobuf::internal::kEmptyString) {
    delete macaroon_;
  }
  if (this != default_instance_) {
  }
}

void e_macaroon::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* e_macaroon::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return e_macaroon_descriptor_;
}

const e_macaroon& e_macaroon::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_e_5fmacaroon_2eproto();
  return *default_instance_;
}

e_macaroon* e_macaroon::default_instance_ = NULL;

e_macaroon* e_macaroon::New() const {
  return new e_macaroon;
}

void e_macaroon::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_macaroon()) {
      if (macaroon_ != &::google::protobuf::internal::kEmptyString) {
        macaroon_->clear();
      }
    }
  }
  endorsements_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool e_macaroon::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string macaroon = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_macaroon()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->macaroon().data(), this->macaroon().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_endorsements;
        break;
      }

      // repeated .macaroons.e_macaroon.Endorsement endorsements = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_endorsements:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_endorsements()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_endorsements;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void e_macaroon::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string macaroon = 1;
  if (has_macaroon()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->macaroon().data(), this->macaroon().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->macaroon(), output);
  }

  // repeated .macaroons.e_macaroon.Endorsement endorsements = 2;
  for (int i = 0; i < this->endorsements_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->endorsements(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* e_macaroon::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string macaroon = 1;
  if (has_macaroon()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->macaroon().data(), this->macaroon().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->macaroon(), target);
  }

  // repeated .macaroons.e_macaroon.Endorsement endorsements = 2;
  for (int i = 0; i < this->endorsements_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->endorsements(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int e_macaroon::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string macaroon = 1;
    if (has_macaroon()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->macaroon());
    }

  }
  // repeated .macaroons.e_macaroon.Endorsement endorsements = 2;
  total_size += 1 * this->endorsements_size();
  for (int i = 0; i < this->endorsements_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->endorsements(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void e_macaroon::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const e_macaroon* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const e_macaroon*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void e_macaroon::MergeFrom(const e_macaroon& from) {
  GOOGLE_CHECK_NE(&from, this);
  endorsements_.MergeFrom(from.endorsements_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_macaroon()) {
      set_macaroon(from.macaroon());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void e_macaroon::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void e_macaroon::CopyFrom(const e_macaroon& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool e_macaroon::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < endorsements_size(); i++) {
    if (!this->endorsements(i).IsInitialized()) return false;
  }
  return true;
}

void e_macaroon::Swap(e_macaroon* other) {
  if (other != this) {
    std::swap(macaroon_, other->macaroon_);
    endorsements_.Swap(&other->endorsements_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata e_macaroon::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = e_macaroon_descriptor_;
  metadata.reflection = e_macaroon_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace macaroons

// @@protoc_insertion_point(global_scope)
